### ISSUE TITLE
Example relationship file?

### ISSUE THREAD

**Issue by arronlacey** [slaverman/SnoLyze#4]
HI slaverman - this is a very impressive implementation of the SNOMED ECL language. One request might be to include a sample relationship file, or indeed the one you have used as an example in the README.md file.

**Comment by slaverman** [comment]
Hi arronlacey, thanks for the compliment! Unfortunately it is not allowed to distrubute the relationship file or even a part of the relationship file. That's why users need to provide a relationship file themselves if they want to use SnoLyze. See https://mlds.ihtsdotools.org/ if your country is a member of SNOMED International or http://www.snomed.org/snomed-ct/get-snomed-ct if your country is not a member of SNOMED International to obtain a relationship file yourself.
